### ISSUE TITLE
How much memory on CUDA?

### ISSUE THREAD

**Issue by RahulBhalley** [balansky/pytorch_gan#1]
I am trying to train this code on Kaggle GPUs (14GB available) but I run out of memory. How much memory does this cGAN with Projection Discriminator network takes for `128x128` resolution image training?

**Comment by balansky** [comment]
It's not support 128 resolution. I only create the resnet for 32 and 64. You need to create your own resnet for 128. You can try https://github.com/pfnet-research/sngan_projection. They support 128 network.

**Comment by RahulBhalley** [comment]
ok.
